## 3. 도형 그리기

### 빈 스케치북 만들기

In [3]:
import cv2
import numpy as np

# 세로 480 가로 640 3channel(BGR) 해당 스케치북
img = np.zeros((480, 640, 3), dtype=np.uint8)

print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [4]:
img[:] = (255, 255, 255)    # 전체 공간을 하얀색으로 채움(b, g, r)
print(img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


### 일부 영역 색칠하기

In [5]:
import cv2
import numpy as np


img = np.zeros((480, 640, 3), dtype=np.uint8)
img[100:200, 200:300] = (255, 255, 255)     # 세로 100~200픽셀까지, 가로 200~300픽셀까지 bgr을 흰색으로 채운다

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 직선
직선의 종류(line type)

1. cv2.LINE_4 : 상하좌우 4방향으로 연결된 선
1. cv2.LINE_8 : 대각선을 포함한 8방향으로 연결된 선 (기본값)
1. cv2.LINE_AA : 부드러운 선 (anti-aliasing)

In [7]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 255)   # b g r : yellow
THICKNESS = 3 # 선 두께

# 그려넣을 스케치북, 시작점, 끝점, 색깔, 두께 선종류
cv2.line(img, (50,100), (400,50), COLOR, THICKNESS, cv2.LINE_8)
cv2.line(img, (50,200), (400,150), COLOR, THICKNESS, cv2.LINE_4)
cv2.line(img, (50,300), (400,250), COLOR, THICKNESS, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 원