## 3. 도형 그리기

### 빈 스케치북 만들기

In [1]:
import cv2
import numpy as np

# 세로 480 가로 640 3channel(BGR) 해당 스케치북
img = np.zeros((480, 640, 3), dtype=np.uint8)

print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [2]:
img[:] = (255, 255, 255)    # 전체 공간을 하얀색으로 채움(b, g, r)
print(img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


### 일부 영역 색칠하기

In [3]:
import cv2
import numpy as np


img = np.zeros((480, 640, 3), dtype=np.uint8)
img[100:200, 200:300] = (255, 255, 255)     # 세로 100~200픽셀까지, 가로 200~300픽셀까지 bgr을 흰색으로 채운다

cv2.imshow('Test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 직선
직선의 종류(line type)

1. cv2.LINE_4 : 상하좌우 4방향으로 연결된 선
1. cv2.LINE_8 : 대각선을 포함한 8방향으로 연결된 선 (기본값)
1. cv2.LINE_AA : 부드러운 선 (anti-aliasing)

In [4]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 255)   # b g r : yellow
THICKNESS = 3 # 선 두께

# 그려넣을 스케치북, 시작점, 끝점, 색깔, 두께 선종류
cv2.line(img, (50,100), (400,50), COLOR, THICKNESS, cv2.LINE_8)
cv2.line(img, (50,200), (400,150), COLOR, THICKNESS, cv2.LINE_4)
cv2.line(img, (50,300), (400,250), COLOR, THICKNESS, cv2.LINE_AA)

cv2.imshow('Test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 원

In [8]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (255, 255, 0)   # BGR 옥색
RADIUS = 50 # 반지름
THICKNESS = 10   # 두께

# 속이 빈 원
# 그릴 위치, 중심점, 반지름, 색깔, 두께, 선종류
cv2.circle(img, (200, 100), RADIUS, COLOR, THICKNESS, cv2.LINE_AA)

# 속이 꽉 찬 원
cv2.circle(img, (400, 100), RADIUS, COLOR, cv2.FILLED, cv2.LINE_AA)

cv2.imshow('Test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 사각형

In [10]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 0)   # BGR 초록색
THICKNESS = 3   # 두께

# 그릴 위치, 시작점 ,끝점, 색깔, 두께
cv2.rectangle(img, (100, 100), (200, 200), COLOR, THICKNESS)    # 속이 빈 사각형
cv2.rectangle(img, (300, 100), (400, 300), COLOR, cv2.FILLED)    # 속이 빈 사각형

cv2.imshow('Test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 다각형

In [25]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR1 = (0, 0, 255)   # BGR 빨간색
COLOR2= (0, 255, 0)   # BGR 초록색
THICKNESS = 3   # 두께

# 이 points들을 잇는 n각형을 만드는 것
pts1 = np.array([[100,100], [200,100], [100,200]])
pts2 = np.array([[300,100], [400,100], [300,200]])

pts3 = np.array([[400,300], [300,300], [300,400]])
pts4 = np.array([[500,300], [600,300], [500,400]])


## 속이 빈 다각형
# 1. 그릴 위치, 다각형 포인트(리스트형), 첫-끝포인트 닫힘여부, 색깔, 두께, 선스타일
cv2.polylines(img, [pts1], True, COLOR1, THICKNESS, cv2.LINE_AA)
cv2.polylines(img, [pts2], False, COLOR1, THICKNESS, cv2.LINE_AA)

# 2. 다각형 포인트는 리스트형이라 한 번에 여러 개를 넣어서 그려도 동일한 결과 출력
cv2.polylines(img, [pts3, pts4], True, COLOR2, THICKNESS, cv2.LINE_AA)


## 속이 꽉 찬 다각형
pts5 = np.array([[[100,300],[200,300],[100,400]], [[200,300],[300,300],[300,400]]])
cv2.fillPoly(img, pts5, COLOR, cv2.LINE_AA)

cv2.imshow('Test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()